Repository Arquisoft/dede_es2c, pull requests merged in 2022-04, with the labels that each got.

#164 Actualización punto 11 de la documentación, argumentos de configuración en Dockerfile y actualización de método update de User
  docker-compose-deploy.yml
  docs/11_technical_risks.adoc
  restapi/Dockerfile
  restapi/server.ts
  restapi/src/controllers/UserController.ts
  restapi/src/model/User.ts
  restapi/src/routes/UserRoutes.ts
  webapp/Dockerfile
  webapp/src/App.tsx
Labels: documentation, code, back-end

#166 Arreglo de la lógica de la app, pruebas unitarias y documentación actualizada
  docs/04_solution_strategy.adoc
  docs/08_concepts.adoc
  docs/12_glossary.adoc
  package-lock.json
  package.json
  restapi/package.json
  restapi/src/controllers/OrderController.ts
  restapi/src/controllers/ProductController.ts
  restapi/src/controllers/UserController.ts
  restapi/src/model/Order.ts
  restapi/src/model/Product.ts
  restapi/src/model/User.ts
  restapi/src/routes/OrderRoutes.ts
  restapi/src/routes/ProductRoutes.ts
  restapi/src/routes/UserRoutes.ts
  restapi/tests/api.test.ts
  restapi/tests/jest.config.ts
  restapi/tests/mockdata/products.json
  restapi/tests/product.test.ts
  webapp/UserContext.ts
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.test.tsx
  webapp/src/App.tsx
  webapp/src/api/api.ts
  webapp/src/components/NavBar.tsx
  webapp/src/components/Products.tsx
  webapp/src/pages/Home.tsx
  webapp/src/pages/ListProducts.tsx
  webapp/src/pages/Pago.tsx
  webapp/src/pages/admin/AddProdcutAdmin.tsx
  webapp/src/pages/admin/ManageOrders.tsx
  webapp/src/pages/admin/ManageProducts.tsx
  webapp/src/pages/admin/OrderAdmin.tsx
  webapp/src/pages/admin/ProdAdmin.tsx
  webapp/src/shared/shareddtypes.ts
  webapp/test/Home.test.tsx
Labels: back-end, test

#167 Test + arreglos
  docs/01_introduction_and_goals.adoc
  docs/03_system_scope_and_context.adoc
  docs/04_solution_strategy.adoc
  docs/08_concepts.adoc
  docs/09_design_decisions.adoc
  docs/12_glossary.adoc
  docs/images/08_VentanaPago.png
  webapp/src/App.test.tsx
  webapp/src/pages/ListProducts.tsx
  webapp/src/pages/admin/AddProdcutAdmin.tsx
  webapp/src/pages/admin/ProdAdmin.tsx
Labels: front-end, test

#169 arreglo usuarios + modelo
  docs/images/08_Modelo_datos.png
  restapi/src/controllers/UserController.ts
  restapi/src/model/User.ts
Labels: bug, back-end

#170 Arreglo de bugs en front + filtro de productos
  restapi/src/controllers/ProductController.ts
  restapi/src/controllers/UserController.ts
  webapp/src/App.test.tsx
  webapp/src/pages/Pago.tsx
Labels: bug, front-end

#172 Actualización punto 5 de la documentación
  docs/05_building_block_view.adoc
  docs/images/05_Whitebox_Overall_System.png
  docs/images/05_building_block_whitebox_level_1.jpg
  restapi/Dockerfile
  restapi/package-lock.json
  restapi/src/controllers/UserController.ts
  restapi/src/model/User.ts
Labels: documentation

#183 Ana
  docs/08_concepts.adoc
  docs/images/08_AdminUsuarios.png
Labels: bug, documentation, despliegue

#184 Developer
  docs/08_concepts.adoc
  docs/images/08_AdminUsuarios.png
Labels: bug, documentation

#205 Cambio de peticiones
  README.md
  README_es.md
  restapi/src/model/Categories.ts
  webapp/src/App.test.tsx
  webapp/src/App.tsx
  webapp/src/api/ApiOrders.ts
  webapp/src/api/ApiProducts.ts
  webapp/src/api/ApiUsers.ts
  webapp/src/components/Footer/Footer.tsx
  webapp/src/components/NavBar.tsx
  webapp/src/img/AL01.jpg
  webapp/src/img/MO01.jpg
  webapp/src/img/RA01.jpg
  webapp/src/img/TE01.jpg
  webapp/src/img/US01.jpg
  webapp/src/pages/Home.tsx
  webapp/src/pages/LogIn.tsx
  webapp/src/pages/Signup.tsx
  webapp/src/pages/admin/AddProdcutAdmin.tsx
  webapp/src/pages/admin/ManageProducts.tsx
  webapp/src/pages/admin/UsersAdmin.tsx
  webapp/src/pages/user/Profile.tsx
  webapp/test/Home.test.tsx
Labels: back-end, front-end, refactorizar

#212 Despliegue en AWS + arreglo fallos en el registro y comprobación del formato del e-mail
  .github/workflows/asw2122.yml
  docker-compose-deploy.yaml
  docker-compose-deploy.yml
  restapi/Dockerfile
  restapi/package-lock.json
  restapi/server.ts
  restapi/src/controllers/UserController.ts
  restapi/src/middlewares/signupValidator.ts
  restapi/src/routes/UserRoutes.ts
  webapp/Dockerfile
  webapp/server.ts
  webapp/src/api/ApiProducts.ts
  webapp/src/api/ApiUsers.ts
  webapp/src/pages/Home.tsx
  webapp/src/pages/Signup.tsx
  webapp/src/pages/admin/ProdAdmin.tsx
  webapp/src/pages/admin/UsersAdmin.tsx
  webapp/src/pages/user/Profile.tsx
Labels: bug, code, back-end, despliegue

#213 Creación de carrito asociado a usuario + rutas de admin duplicadas
  restapi/package-lock.json
  restapi/server.ts
  restapi/src/controllers/CartController.ts
  restapi/src/controllers/UserController.ts
  restapi/src/model/Cart.ts
  restapi/src/routes/CartRoutes.ts
  webapp/src/App.tsx
  webapp/src/api/ApiUsers.ts
Labels: bug, code, back-end

#216 Backend para guardar los carritos en base de datos
  restapi/src/controllers/CartController.ts
  restapi/src/model/Cart.ts
  restapi/src/routes/CartRoutes.ts
Labels: code, back-end

#218 Ana
  README.md
  README_es.md
  restapi/src/controllers/ProductController.ts
  restapi/src/routes/ProductRoutes.ts
  webapp/UserContext.ts
  webapp/src/App.test.tsx
  webapp/src/App.tsx
  webapp/src/api/ApiProducts.ts
  webapp/src/components/NavBar.tsx
  webapp/src/components/Products.tsx
  webapp/src/components/admin/AddProduct.tsx
  webapp/src/components/utils/HelpButton.tsx
  webapp/src/pages/Home.tsx
  webapp/src/pages/LogIn.tsx
  webapp/src/pages/Pago.tsx
  webapp/src/pages/ProductDetails.tsx
  webapp/src/pages/Signup.tsx
  webapp/src/pages/admin/AddProdcutAdmin.tsx
  webapp/src/pages/utils/HelpPage.tsx
  webapp/src/pages/utils/NoPermissions.tsx
  webapp/src/tests/HomeTest.test.tsx
  webapp/src/tests/LogIn.test.tsx
  webapp/src/tests/Pago.test.tsx
  webapp/src/tests/Products.test.tsx
  webapp/src/tests/SignUp.test.tsx
  webapp/src/tests/admin/AddProduct.test.tsx
  webapp/src/tests/admin/AdminProducts.test.tsx
  webapp/src/tests/admin/Orders.test.tsx
  webapp/src/tests/components/Footer.test.tsx
  webapp/src/tests/utils/HelpPage.test.tsx
  webapp/src/tests/utils/NoPermissions.test.tsx
Labels: front-end

#220 Modificación del .yml para incluir test de frontend + findUsersbyId
  .github/workflows/asw2122.yml
  restapi/src/routes/UserRoutes.ts
Labels: code, back-end, despliegue
