Repository Arquisoft/dede_es2c, pull requests merged in 2022-03, with the labels that each got.

#66 Punto de partida para el backend
  package-lock.json
  package.json
  restapi/server.ts
  restapi/src/controllers/UserController.ts
  restapi/src/model/User.ts
  restapi/src/routes/UserRoutes.ts
Labels: code, back-end

#67 Ana
  package.json
  restapi/img/AL01.jpg
  restapi/img/MO01.jpg
  restapi/img/RA01.jpg
  restapi/img/TE01.jpg
  restapi/img/US01.jpg
  restapi/package-lock.json
  restapi/package.json
  restapi/server.ts
  restapi/src/controllers/ProductController.ts
  restapi/src/model/Product.ts
  restapi/src/routes/ProductsRoutes.ts
Labels: review, back-end

#69 Commit para probar el despliegue del carrito
  package.json
  restapi/src/controllers/ShoppingCartController.ts
  restapi/src/model/ShoppingCart.ts
  restapi/src/routes/ShoppingCartRoutes.ts
Labels: review, back-end

#70 Cambio carrito por pedido
  package-lock.json
  package.json
  restapi/server.ts
  restapi/src/controllers/OrderController.ts
  restapi/src/controllers/ProductController.ts
  restapi/src/controllers/ShoppingCartController.ts
  restapi/src/model/Order.ts
  restapi/src/model/ShoppingCart.ts
  restapi/src/routes/OrderRoutes.ts
  restapi/src/routes/ProductsRoutes.ts
  restapi/src/routes/ShoppingCartRoutes.ts
Labels: back-end

#78 Base para el front
  package-lock.json
  package.json
  webapp/package-lock.json
  webapp/package.json
  webapp/public/index.html
  webapp/public/logo-peq.png
  webapp/src/App.tsx
  webapp/src/checks/Arguments.ts
  webapp/src/components/Welcome.tsx
  webapp/src/img/logo-dede.svg
  webapp/src/index.tsx
  webapp/src/pages/Home.tsx
  webapp/src/pages/LogIn.tsx
  webapp/src/pages/Singup.tsx
Labels: front-end

#84 Adrian
  docs/images/protHome.jpg
  docs/images/protListaProd.jpg
  docs/images/protLogin+SingUp.jpg
  package-lock.json
  package.json
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.tsx
  webapp/src/pages/Products.tsx
  webapp/src/pages/Signup.tsx
  webapp/src/pages/Singup.tsx
Labels: documentation, code, review, front-end

#88 CRUD de usuarios + primera conexión backend y frontend
  package-lock.json
  package.json
  restapi/package-lock.json
  restapi/package.json
  restapi/server.ts
  restapi/src/controllers/UserController.ts
  restapi/src/model/Order.ts
  restapi/src/model/User.ts
  restapi/src/routes/OrderRoutes.ts
  restapi/src/routes/UserRoutes.ts
  webapp/src/pages/LogIn.tsx
Labels: code, back-end

#93 Ana
  docs/08_concepts.adoc
  docs/12_glossary.adoc
  docs/images/08_protHome.jpg
  docs/images/08_protListaProd.jpg
  docs/images/08_protLogin+SingUp.jpg
  package-lock.json
  package.json
  restapi/src/controllers/ProductController.ts
  restapi/src/routes/ProductsRoutes.ts
  webapp/src/App.tsx
  webapp/src/api/api.ts
  webapp/src/components/Filters.tsx
  webapp/src/components/NavBar.tsx
  webapp/src/components/Products.tsx
  webapp/src/pages/Home.tsx
  webapp/src/pages/ListProducts.tsx
  webapp/src/pages/Products.tsx
  webapp/src/shared/shareddtypes.ts
Labels: documentation, review, back-end, front-end

#98 Registro conectado con el backend + avisos y comprobaciones en login y registro
  restapi/src/controllers/UserController.ts
  restapi/src/routes/UserRoutes.ts
  webapp/src/pages/LogIn.tsx
  webapp/src/pages/Signup.tsx
Labels: code, back-end

#100 Efrén
  docs/08_concepts.adoc
  docs/images/Modelo_datos.png
  restapi/src/controllers/OrderController.ts
  restapi/src/controllers/ProductController.ts
  restapi/src/model/Order.ts
  restapi/src/routes/ProductsRoutes.ts
Labels: review, back-end, front-end

#111 Ana
  restapi/server.ts
  webapp/src/components/Products.tsx
  webapp/src/pages/ListProducts.tsx
Labels: back-end, front-end

#139 Para Probar los pedidos
  .github/workflows/dede_es2c.yml
  restapi/server.ts
  restapi/src/controllers/OrderController.ts
  restapi/src/controllers/ProductController.ts
  restapi/src/model/Order.ts
  restapi/src/model/Product.ts
  restapi/src/routes/OrderRoutes.ts
  restapi/src/routes/ProductsOrderRoutes.ts
  restapi/tests/mockdata/products.json
  restapi/tests/product.test.ts
Labels: back-end, front-end

#140 Ana
  .github/workflows/dede_es2c.yml
  docs/index.adoc
  restapi/server.ts
  restapi/src/controllers/OrderController.ts
  restapi/src/controllers/ProductController.ts
  restapi/src/model/Order.ts
  restapi/src/model/Product.ts
  restapi/src/routes/OrderRoutes.ts
  restapi/src/routes/ProductsOrderRoutes.ts
  restapi/tests/mockdata/products.json
  restapi/tests/product.test.ts
  webapp/src/App.tsx
  webapp/src/api/api.ts
  webapp/src/components/ProductosPorFiltro.tsx
  webapp/src/components/Products.tsx
  webapp/src/components/admin/StackAdmin.tsx
  webapp/src/pages/ListProducts.tsx
  webapp/src/pages/admin/AddProdcutAdmin.tsx
  webapp/src/pages/admin/ManageOrders.tsx
  webapp/src/pages/admin/ManageProducts.tsx
  webapp/src/pages/admin/OrderAdmin.tsx
  webapp/src/pages/admin/ProdAdmin.tsx
  webapp/src/shared/shareddtypes.ts
Labels: back-end, front-end

#143 Efrén
  docs/01_introduction_and_goals.adoc
  docs/08_concepts.adoc
  docs/images/08_Modelo_datos.png
  restapi/server.ts
  restapi/src/controllers/OrderController.ts
  restapi/src/controllers/ProductController.ts
  restapi/src/controllers/ProductOrderController.ts
  restapi/src/model/Order.ts
  restapi/src/model/Product.ts
  restapi/src/model/ProductOrder.ts
  restapi/src/routes/OrderRoutes.ts
  restapi/src/routes/ProductOrderRoutes.ts
  restapi/src/routes/ProductRoutes.ts
  restapi/src/routes/ProductsOrderRoutes.ts
Labels: back-end, front-end

#145 Ana
  docs/04_solution_strategy.adoc
  docs/08_concepts.adoc
  docs/12_glossary.adoc
  docs/images/08_AdminAnadirProducto.png
  docs/images/08_CatalogoProductos.png
  docs/images/08_HomePage.png
  docs/images/08_IniciarSesion.png
  docs/images/08_ModalActualizacionProd.png
  docs/images/08_OrderAdmin.png
  docs/images/08_ProdAdmin.png
  docs/images/08_Registro.png
  docs/images/0_8AdminUsuarios.png
  webapp/src/App.tsx
  webapp/src/components/NavBar.tsx
  webapp/src/components/Products.tsx
  webapp/src/pages/ListProducts.tsx
  webapp/src/pages/Pago.tsx
  webapp/src/pages/Products.tsx
  webapp/src/pages/ProductsSummary.tsx
  webapp/src/pages/admin/IUserAdmin.tsx
  webapp/src/pages/admin/OrderAdmin.tsx
  webapp/src/pages/admin/UsersAdmin.tsx
  webapp/src/shared/shareddtypes.ts
Labels: back-end, front-end

#151 Efrén
  restapi/package.json
  restapi/src/controllers/OrderController.ts
  restapi/src/controllers/ProductController.ts
  restapi/src/controllers/UserController.ts
  restapi/src/model/Order.ts
  restapi/src/model/Product.ts
  restapi/src/model/User.ts
  restapi/src/routes/OrderRoutes.ts
  restapi/src/routes/ProductRoutes.ts
  restapi/tests/api.test.ts
  restapi/tests/jest.config.ts
  restapi/tests/product.test.ts
Labels: back-end, front-end

#154 Arreglo de registro y creación de método para dar permisos de administrador a otro usuario
  restapi/package-lock.json
  restapi/package.json
  restapi/src/controllers/UserController.ts
  restapi/src/model/User.ts
  restapi/src/routes/UserRoutes.ts
  webapp/src/pages/Signup.tsx
Labels: back-end, front-end

#159 Efrén
  restapi/src/controllers/OrderController.ts
  restapi/src/controllers/ProductController.ts
  restapi/src/routes/ProductRoutes.ts
  restapi/tests/api.test.ts
  restapi/tests/jest.config.ts
Labels: back-end, front-end
